omise/omise-android

.idea/misc.xml
README.md
app/src/main/java/co/omise/android/example/MainActivity.java
app/src/main/res/menu/menu_main.xml
app/src/main/res/values/strings.xml
build.gradle
sdk/build.gradle
sdk/src/main/AndroidManifest.xml
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.java
sdk/src/main/res/layout/activity_authorizing_payment.xml
sdk/src/main/res/values-ja/strings.xml
sdk/src/main/res/values-th/strings.xml
sdk/src/main/res/values/strings.xml

Since the Authorizing Payment is a common operation when using Omise service now. I think it would be great if we have the built-in way to support the Authorizing Payment in the SDK.
This PR introduces the `AuthorizingPaymentActivity` scene which replaces the old `Verify3DSActivity`. This new OmiseAuthorizingPaymentViewController requires the expected return URL patterns in order to make it work properly. The merchants/library-users need to specify their return URL patterns to this scene.

Built-in Authorizing Payment scene

---

README.md
sdk/build.gradle
sdk/proguard-rules.pro

To support Android ProGuard. 
- Added rules for SDK's ProGuard
- Added documentation for using SDK with ProGuard
**3. How to test**
- On Android Studio in the sample project you can enable ProGuard by open `build.gradle` in sample project and edit `minifyEnabled` to `true`. 
- Change variant to `release`. 
- Create keystore for testing and add keystore config to `build.gradle` [more detail](https://developer.android.com/studio/publish/app-signing.html).
- On Android Studio toolbar `Build>Build APK` this will create release apk file.

Added ProGuard

---

build.gradle
sdk/build.gradle
sdk/src/androidTest/java/co/omise/android/CreditCardEditTextTest.java
sdk/src/debug/AndroidManifest.xml
sdk/src/debug/java/co/omise/android/TestCreditCardEditTextActivity.java
sdk/src/debug/res/layout/activity_test_credit_card_edit_text.xml
sdk/src/debug/res/values/strings.xml
sdk/src/main/java/co/omise/android/ui/CreditCardEditText.java

This PR fixed issue #27. Because of `OnKeyListener` will fired only hardware keyboard and not working with alternative keyboards. To solve format on `CreditCardEditText`, use `TextWatcher` instead of `OnKeyListener` to format credit card number.

Fix credit card number format.

---

README.md
app/src/main/AndroidManifest.xml
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.java

Supported authorize URI with external app, for example Alipay app. `AuthrizingPaymentActivity` automatically open external app when authorize URI was not `https, http, about` scheme. When user confirmed payment from external app, then will pass result back to `onActivityResult()` in merchant app.

Handle authorize uri with external app

---

README.md
app/src/main/java/co/omise/android/example/CheckoutActivity.java
sdk/src/main/java/co/omise/android/ui/CreditCardActivity.java

Small PR where we've changed the behavior of `CreditCardActivity` to setResult using the default codes provided by the SDK instead of custom codes. 
Task -> https://phabricator.omise.co/T7791

CreditCardActivity setResult change

---

sdk/src/main/java/co/omise/android/ui/NumberRangeSpinnerAdapter.java
sdk/src/main/res/layout/activity_credit_card.xml

There is an issue for some device (e.g. Samsung). The expiry date spinner doesn't display default expiry date.
Seems to be the issue raised from using `simple_spinner_dropdown_item` on the default view. To solved this issue, had changed the default layout to `simple_spinner_item`.
The default spinner view should show for all device.

Fix spinner default view

---

sdk/build.gradle
sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt
sdk/src/main/java/co/omise/android/extensions/StringExtensions.kt
sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
sdk/src/main/java/co/omise/android/ui/OmiseEditText.kt
sdk/src/main/res/layout/activity_credit_card.xml
sdk/src/main/res/values-ja/strings.xml
sdk/src/main/res/values-th/strings.xml
sdk/src/main/res/values/colors.xml
sdk/src/main/res/values/dimen.xml
sdk/src/main/res/values/ids.xml
sdk/src/main/res/values/strings.xml
sdk/src/main/res/values/styles.xml
sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt
sdk/src/test/java/co/omise/android/extensions/APIErrorExtensionsTest.kt
sdk/src/test/java/co/omise/android/ui/OmiseEditTextTest.kt
sdk/src/test/resources/data/objects/error_object.json

**Invalid input error**
As the team discussed, we decided to separate the error text from `OmiseEditText`.
**API request error**
Follow the new design. It changes to use `Snackbar` to show the error message from API request error.
**Invalid input error**
To show the invalid input error on CreditCardActivity, added the TextViews under the EditTexts. And deleted the error text from `OmiseEditText`.
**API request error**
Show error message on Snackbar when creating a token return an error from request.
When the user enter invalid inputs or got error from request the CreditCardActivity will show error messages follow the image.

Revise credit card error messages

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/res/color/button_text_color.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml
sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
sdk/src/main/java/co/omise/android/ui/CreditCardEditText.kt
sdk/src/main/java/co/omise/android/ui/OmiseEditText.kt
sdk/src/main/res/drawable/bg_button.xml
sdk/src/main/res/drawable/bg_edit_text_outlined.xml
sdk/src/main/res/layout/activity_credit_card.xml
sdk/src/main/res/values-ja/strings.xml
sdk/src/main/res/values-th/strings.xml
sdk/src/main/res/values/attrs.xml
sdk/src/main/res/values/colors.xml
sdk/src/main/res/values/dimens.xml
sdk/src/main/res/values/strings.xml
sdk/src/main/res/values/styles.xml
sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt
sdk/src/test/java/co/omise/android/ui/CreditCardEditTextTest.kt

From previous PRs, we provided basically function for creating the Token via the `CreditCardActivity`. So, this PR continue theming the `CreditCardActivity` to provide the theme and able to custom the theme. 
On this PR, I renamed the default theme from `OmiseSDKTheme` to better name `OmiseTheme`. Android provided style follow the design.
Custom theme, this PR declared new attributes to able set styles on the `CreditCardActivity`. After the user set styles to attributes on their theme, the layout should apply the set of styles via declared attributes.
```xml
<attr name="omiseButtonStyle" format="reference" />
<attr name="omiseEditTextStyle" format="reference" />
<attr name="omiseEditTextLabelStyle" format="reference" />
<attr name="omiseEditTextErrorStyle" format="reference" />
```
In …

Theming credit card form

---

sdk/src/main/java/co/omise/android/Client.java

In the old way we used the certificate pinning to prevent Man in the Middle(MITM) attack to secure our requests. OSes nowadays there's new way to help to prevent MITM attack.
So, we decided to remove the certificate pinning from build-in library and use the default certificate
that provide from the OSes or their system instead.

Remove certificate pinning

---

sdk/src/main/java/co/omise/android/models/FlowType.kt
sdk/src/test/java/co/omise/android/SerializationTest.java

**TASK**=>T13872
**SUMMARY**
Small PR to fix an issue where a missing `@JsonValue` annotation in `FlowType`'s constructor was causing the the Serialization test to crash.

Fix serialization test

---

sdk/src/main/java/co/omise/android/models/Capability.kt
sdk/src/main/java/co/omise/android/models/Card.kt
sdk/src/main/java/co/omise/android/models/Model.kt
sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
sdk/src/main/java/co/omise/android/models/References.kt
sdk/src/main/java/co/omise/android/models/Source.kt
sdk/src/main/java/co/omise/android/models/Token.kt
sdk/src/test/java/co/omise/android/ParcelableTest.kt

**TASK**=>T16075
**SUMMARY**
Small PR to make all the data models in the SDK immutable.
🦑 **NOTE** 🦑
It was initially planned to also remove initial values from the properties and make them non-nullable as a result, but that caused crashes due to internal issues in `Jackson`, so they are kept the way they are till a workaround for that issue can be found.

Model immutability

---

app/src/main/java/co/omise/android/example/CheckoutActivity.java
app/src/main/java/co/omise/android/example/MainActivity.java
sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
sdk/src/main/java/co/omise/android/ui/OmiseActivity.kt
sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt
sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
sdk/src/sharedTest/java/co/omise/android/ui/PaymentCreatorActivityTest.kt

Continue implementing the payment creator by this PR implement creating a payment from the existed credit card form.
From the payment chooser, when the user pressed the credit card method, it will navigate to `CreditCardActivity`  and return a token result when creating token success.
On the sample app, when creating a payment from the credit card form will get a Token as a response.

Create payment from credit card

---

sdk/src/main/java/co/omise/android/models/SourceType.kt
sdk/src/main/java/co/omise/android/ui/InstallmentChooserFragment.kt
sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt
sdk/src/main/java/co/omise/android/ui/InternetBankingChooserFragment.kt
sdk/src/main/java/co/omise/android/ui/OmiseFragment.kt
sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
sdk/src/main/res/values/strings.xml
sdk/src/sharedTest/java/co/omise/android/ui/InstallmentChooserFragmentTest.kt
sdk/src/sharedTest/java/co/omise/android/ui/InstallmentTermChooserFragmentTest.kt
sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
sdk/src/sharedTest/java/co/omise/android/ui/TestFragmentActivity.kt

Create the installment chooser page to able users to create a payment from the installment method.
In this PR create new 2 pages for the flow. The first page is `InstallmentChooserFragment` for choosing a bank issuer. 
And the second page is `InstallmentTermChooserFragment` for choosing an installment term. After the user chose an installment term, it will send a request to create a source object.
To test creating a source from the installment method, you can open the sample app and choose the installment method. Then choose a bank issuer and installment term it should return source object.

Create payment from installment

---

sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
sdk/src/main/java/co/omise/android/models/SourceType.kt
sdk/src/main/java/co/omise/android/ui/EContextFormFragment.kt
sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt
sdk/src/main/java/co/omise/android/ui/InternetBankingChooserFragment.kt
sdk/src/main/java/co/omise/android/ui/OmiseFragment.kt
sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
sdk/src/main/res/layout/fragment_econtext_form.xml
sdk/src/main/res/values/dimens.xml
sdk/src/main/res/values/strings.xml
sdk/src/sharedTest/java/co/omise/android/ui/EContextFormFragmentTest.kt
sdk/src/sharedTest/java/co/omise/android/ui/InstallmentChooserFragmentTest.kt
sdk/src/sharedTest/java/co/omise/android/utils/ViewUtils.kt

To able users create a payment from Convenience Store / Pay-easy / Netbanking in the payment chooser page.
When the user pressed Convenience Store / Pay-easy / Netbanking in the payment chooser page, it will display a form that required full-name, email, phone number. When the user pressed the next button, it will send a request to create a source with information in the form.
When the user entered valid information, it will send a request and return a source object.
If there is invalid information, the submit button will disable to press til the user enter valid data.

Create payment from EContext

---

sdk/src/main/java/co/omise/android/ui/OmiseListFragment.kt

To put the line diver between items in RecyclerView.
In this OR created `OmiseItemDecoration` class that set the starting line from title to end of the item. And set it to OmiseListFragment's recyclerView. Every children class will automatically apply this item decoration.
All pages that have list view should show line divider between items.

Added ItemDecoration to RecyclerView.

---

sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt
sdk/src/sharedTest/java/co/omise/android/ui/EContextFormFragmentTest.kt
sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
sdk/src/test/resources/robolectric.properties

To able users to send a request to create a source object from Alipay and Bill Payment Tesco Lotus.
Set the event when the user press on Alipay or Bill Payment Tesco Lotus from the payment chooser page. It will send a request with the source type to create a source object.
When the user press on Alipay or Bill Payment Tesco Lotus it will return a source object.

Create payment from Alipay / Bill payment Tesco Lotus

---

sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt
sdk/src/main/java/co/omise/android/models/Amount.kt
sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
sdk/src/main/res/values-ja/strings.xml
sdk/src/main/res/values-th/strings.xml
sdk/src/main/res/values/strings.xml
sdk/src/test/java/co/omise/android/extensions/APIErrorExtensionsTest.kt

To display error messages from creating source API.
In this PR mapped error messages from API to messaging resources if error messages not matched, it will use the origin error message. And, displayed the Snackbar with the error message when request failed.
When a request was failed, it should display the Sankbar with the error message

Payment creator handle error messages

---

app/src/main/res/layout/activity_checkout.xml

In case the sample app runs on a small screen device, the UI overlapped on the screen. So, in this PR updated `activity_checkout.xml` layout by wrap screen with ScrollView.

Update sample app's layout to support small screen

---

sdk/src/main/java/co/omise/android/models/CardBrand.kt

Since Laser debit card discontinued since 2014, we decided to drop support it.

Droped support Laser debit card.

---

build.gradle
sdk/src/main/java/co/omise/android/api/Configurer.kt
sdk/src/main/java/co/omise/android/api/Invocation.kt
sdk/src/main/java/co/omise/android/api/RequestBuilder.kt

As team discussed SDK needs to support Android 4.1 (API 16). So, we need to downgraded **OkHttp** to version 3 cause version 4 support Android 5.1 (API 21) above. 
> ### IMPORTANT NOTE 🚨
> However, **OkHttp** version 3 will support until December 31, 2020 https://github.com/square/okhttp#requirements. SDK might needs to upgrade minimum version in the future.

Downgrade OkHttp to version 3

---

app/src/main/res/layout/activity_checkout.xml
sdk/src/main/res/drawable-v21/bg_edit_text_outlined.xml
sdk/src/main/res/values/styles.xml

Bug fixes using `OmiseTheme` on Android 4.1 cause API lower 21 is not supported refer `@color` in **Drawable** resource.
In this PR created separated **Drawable** resource for API 21. And, created `bg_edit_text_outlined.xml` that using code color instead of color reference.
The sample shall run the app with **OmiseTheme** with no crash on Android 4.1.

Fixed OmiseTheme to support Android 4.1.

---

app/src/main/java/co/omise/android/example/PaymentSetting.kt
app/src/main/java/co/omise/android/example/PaymentSettingFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/preference_payment_setting.xml
sdk/src/main/java/co/omise/android/models/Capability.kt
sdk/src/main/java/co/omise/android/models/Source.kt
sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt
sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
sdk/src/sharedTest/java/co/omise/android/ui/InstallmentTermChooserFragmentTest.kt

To able the payment creator accepts the `zeroInterestInstallments` parameter if it present in the `Capability` object.
In the `InstallmentTermChooserFragment`, correct the `zeroInterestInstallments` parameter from the `Capability` object and set it into the source request. 
Also, added `zeroInterestInstallments` setting into the payment settings in the sample app. 
When create a source via the payment creator, the payment creator should return a source response that contains `zeroInterestInstallments` value same in the request.
N/A
N/A
Normal

T20318 - Support zero interest installments in the payment creator

---

sdk/src/main/java/co/omise/android/models/Serializer.kt
sdk/src/main/java/co/omise/android/models/Source.kt
sdk/src/test/java/co/omise/android/SerializationTest.java

To fix creating source received a response that contains unrelated the parameters.
In this PR rid of default value from the create source parameters to prevent create a source with default field values.
When create a new source, the response shouldn't contains fields that unrelated to the parameters.
N/A
N/A
Normal

T20531 - Fix creating source

---

sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt

In this PR purpose to enable local storage to support the authorize URI that required to use local cache on the WebView. However, the local cache life time will limit only while authorizing URI flow. After completed authorize URI the WebView will clear all cache.
Reference: https://developer.android.com/training/articles/security-tips#WebView
Enabled cache on the WebView in the **AuthorizingPaymentActivity**.  And clean cache after the Activity was destroyed.
The authorize URI that required to use local cache shall be able to proceed.
N/A
N/A
High

Enable WebView's local storage

---

sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt

To initialize the 3DS SDK in the `AuthorizingPaymentActivity` class. 
In this PR add thee `ThreeDS` to the `AuthorizingPaymentActivity` properties. And implemented `ThreeDSAuthorizingTransactionListener` for listening result from the `ThreeDS`.
N/A
N/A
N/A
N/A
N/A
N/A

Initialize 3DS SDK

---

sdk/src/main/java/co/omise/android/models/ChargeStatus.kt
sdk/src/main/java/co/omise/android/models/Source.kt
sdk/src/main/java/co/omise/android/models/Token.kt
sdk/src/test/resources/data/objects/source_object.json

This PR purpose to able the SDK to retrieve a particular source object with the Source ID.
Create the `GetSourceRequestBuilder` request class. And add the `charge_status` field to the Source model.
**Request sample**
```kotlin
val sourceRequest = Source.GetSourceRequestBuilder("src_test_1234").build()
client.send(sourceRequest, object : RequestListener<Source> {
override fun onRequestSucceed(model: Source) {
...
}
override fun onRequestFailed(throwable: Throwable) {
...
}
})
```
N/A
N/A
N/A
N/A
N/A

Retrieving a source request

---

sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt

To update the implementation the `ThreeDSListener` interface to use the latest version of 3DS SDK.
- Update `ThreeDSListener` implementation.
- Show progress bar while 3DS processing.
N/A
N/A
N/A
N/A
N/A
N/A

Update 3DS listener implmentation

---

build.gradle
gradle.properties
sdk/build.gradle
sdk/src/main/java/co/omise/android/api/Client.kt
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentViewModel.kt
sdk/src/main/java/co/omise/android/ui/OmiseActivity.kt

After the 3DS SDK returned the result and the result is authenticated, the SDK should observe the charge's status from the Token API until the change status updated or timed out.
When the 3DS SDK invokes `onAuthenticated()`, the SDK will observe the charge's status from by sending request to Token API to get the latest status. If the charge's status is `pending` or `unknown`, the SDK will interval every 3 seconds until the charge's status changed. The SDK will return the timeout error if exceeds 30 seconds.
N/A
There are 2 new parameters that required from the requestor app.
- `EXTRA_TOKEN` the token ID.
- `EXTRA_PKEY` the public key.
N/A
N/A
N/A
N/A

Observe token

---

app/src/main/java/co/omise/android/example/PaymentSetting.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/preference_payment_setting.xml
sdk/src/main/java/co/omise/android/models/SourceType.kt
sdk/src/main/java/co/omise/android/ui/InstallmentChooserFragment.kt
sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt
sdk/src/main/res/values-ja/strings.xml
sdk/src/main/res/values-th/strings.xml
sdk/src/main/res/values/strings.xml
sdk/src/sharedTest/java/co/omise/android/ui/InstallmentChooserFragmentTest.kt
sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt

Add Installment SCB support
- Added Installment SCB support to payment methods
Make sure Installment SCB can be selected and sources can be created.
When choosing Capability API:
When choosing Specific payment method:
N/A
N/A
N/A
N/A
N/A

Add installment SCB support

---

.github/workflows/cd.yml
.github/workflows/ci.yml
sdk/build.gradle

There's failed build from building the `sdk` module. That was blocked the GithubActions from auto upload the new Omise SDK version to Sonatype. So, this PR purpose to fix the failed build and able to automate the workflow again.
Related PR: #168 #167 
- Remove multidex from `build.gradle`
- Add the build step in CI/CD workflows
GithubActions shall be run all workflows without failed build.
N/A
N/A
N/A
N/A
N/A

Fix build failed

---

.github/workflows/cd.yml
.github/workflows/ci.yml
app/build.gradle
build.gradle
gradle.properties
sample-threeds-v2-app/build.gradle
sdk/build.gradle
sdk/src/main/java/co/omise/android/api/EndPoint.kt
sdk/src/production/java/co/omise/android/api/OmiseEndpoints.kt
sdk/src/staging/java/co/omise/android/api/OmiseEndpoints.kt
sdk/src/test/java/co/omise/android/ConfigurerTest.java
testsupport/build.gradle

To enhance the internal testing flow to be able to build the Omise Android with staging environment.
This PR created a new `mode` dimension that contains `production` and `staging` flavors. And extracted the endpoints from the codebase to `OmiseEndpoints` file on specific build flavor path.
**For sample:** 
production: `sdk/src/production/java/co/omise/android/api/OmiseEndpoints.kt`
staging: `sdk/src/staging/java/co/omise/android/api/OmiseEndpoints.kt`
In the case you want to test with staging environment, you can change the value in `sdk/src/staging/java/co/omise/android/api/OmiseEndpoints.kt` path. And in the build variant choose `StagingDebug` in the case for debug mode. So now you can run the sample app and put the public key for staging environment and you can test create token and …

Support build with staging environment

---

build.gradle
sdk/src/androidTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt
sdk/src/main/java/co/omise/android/OmiseError.kt
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt
sdk/src/main/java/co/omise/android/ui/OmiseActivity.kt

This PR purpose to change the failure result from the error message to error object.
Updated the failure result from the 3DS process to return the failure object from the 3DS SDK.
N/A
N/A
N/A
N/A
N/A
N/A

Revise 3DS failure result

---

build.gradle
sdk/src/main/java/co/omise/android/ui/CardNameEditText.kt
sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt
sdk/src/main/java/co/omise/android/ui/OmiseEditText.kt
sdk/src/main/java/co/omise/android/ui/SecurityCodeEditText.kt

To fix a bug from inflating the WebView in the AuthorizingPaymentActivity on Android 5.0.
issue: #177 
Regarding to [issue](https://issuetracker.google.com/issues/141351441#comment35) from the Appcompat version 1.1.0 that related to the crash on inflating the WebView. So, in this PR the Appcompat version was updated to use version 1.2.0 that fixed the issue. 
When authorize the `authorize_uri` with AuthorizingPaymentActivity, it shall be performed the authorization without the crash about inflating the WebView.
N/A
N/A
N/A
N/A
N/A

Fix can not open WebView on Android 5.0

---

CHANGELOG.md
build.gradle

To bump the Omise Android to new version.
Bumped  the Omise Android to version 3.2.1.
N/A
N/A
N/A
N/A
N/A
N/A

Bump version 3.2.1

---

.github/workflows/cd.yml
app/build.gradle
sdk/build.gradle

Since the `maven` plugin ([link](https://docs.gradle.org/current/userguide/maven_plugin.html)) is deprecated. The Omise Android SDK will not be able to publish package with `maven` plugin anymore. The Omise Android SDK needs to migrate to use `maven-publish` plugin instead.
In this PR migrated the publish configuration in the `sdk/build.gradle` file to use the `maven-publish` plugin. Also, update the command of **Maven Package** workflow to use `./gradlew sdk:publish` command.
To upload package to staging repositories on the Sonatype.
```
./gradlew sdk:publish
```
To test uploading package on your local machine. It will publish to this path `~/.m2/repository`.
```
./gradlew sdk:publishToMavenLocal
```
N/A
N/A
N/A
N/A
N/A

Maven publish

---

sdk/build.gradle

Regarding to PR #184 after uploaded artifact with `maven-publish` plugin to Sonatype and then close the repository. There is a failed process during signing the artifact that blocked Sonatype to release the repository.
Related PR: #184 
In this PR fixed the signing tasks in `sdk/build.gradle` to sign the `release` function thate located inside the `publications` block.
When click close the repository in Sonatype, all precesses shall be passed.
N/A
N/A
N/A
N/A
N/A

Fix signing artifact

---

CHANGELOG.md
build.gradle

* **CHANGED:** Require minimum SDK version 21
* **ADDED:** 3D Secure version 2
* **ADDED:** Observing `ChargeStatus` change with Token ID
* **ADDED:** `platform_type` field for Source
* **ADDED:** Support for wallets: Alipay (SG), AlipayHK (SG), DANA (SG), GCash (SG), Kakao Pay (SG), Touch'n Go (SG) and Rabbit LINE Pay (TH)
* **ADDED:** Support for installments: Citi (TH), TTB (TH), UOB (TH) and Ezypay (MY)
* **ADDED:** Support for mobile banking payments: Kbank (TH), Bay (TH) and OCBC Pay Anyone (SG)

v4.0.0 Release

---

CHANGELOG.md
build.gradle

* **ADDED:** Added support for Boost, DuitNow QR, DuitNow Online Banking/Wallets, Maybank QRPay and ShopeePay payment method.
* **CHANGED** Update Touch 'n Go and Grabpay to support RMS provider.

Release v4.2.0

---

sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt

Fix where webview explicitly throws error to user upon custome scheme navigation

[APM2-1427] Don't explicitly throw redirect error

---

CHANGELOG.md
build.gradle

* **FIXED:** Patch explicit error thrown when redirecting to non-existing custom scheme uri
Related PR: https://github.com/omise/omise-android/pull/243

4.5.1 Release

---

app/src/main/java/co/omise/android/example/PaymentSetting.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/preference_payment_setting.xml
sdk/src/main/java/co/omise/android/models/SourceType.kt
sdk/src/main/java/co/omise/android/ui/PaymentMethodResources.kt
sdk/src/main/res/values-ja/strings.xml
sdk/src/main/res/values-th/strings.xml
sdk/src/main/res/values/strings.xml
sdk/src/sharedTest/java/co/omise/android/ui/InternetBankingChooserFragmentTest.kt
sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt

To remove KTB and SCB internet bankings, regarding the SCB and KTB internet banking decommission.
Task: https://opn-ooo.atlassian.net/browse/EM-2786
Results: 
SCB and KTB internet banking do not appear in payment methods selection both user setting page and payment page.

[EM-2969] Remove KTB and SCB internet bankings

---

.github/workflows/ci.yml
app/build.gradle
build.gradle
sdk/build.gradle
sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
testsupport/build.gradle

This PR upgraded `threeds-android` dependency to vresion 1.0.0-alpha12. 
**Minimum requirements**
- Kotlin version 1.7.10 or above.
- Android gradle plugin version 7.4.2 or above.

[MIT-1378] Upgrade 3DS-SDK version 1.0.0-alpha12

---

.github/workflows/cd.yml

Due to a build failed on CD pipeline [link](https://github.com/omise/omise-android/actions/runs/5262682228), this PR upgrades JDK to version 11 because AGP 7.4 is no longer supported JDK 1.8.

Upgrade JDK to version 11 on CD pipeline

---

CHANGELOG.md
build.gradle

- chore: bump omise sdk to version 4.10.0
- docs: update CHANGELOG.md

Bump version 4.10.0

---

sdk/src/androidTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt

In order to fix the app crash when hiding after closing the transaction, so we can remove calling `hideProgress()` because when closing the transaction it will also hide the progress view.

[MIT-1925] Fix app crash from progress view

---

README.md
sdk/src/androidTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt
sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
sdk/src/main/java/co/omise/android/ui/OmiseActivity.kt
sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt
sdk/src/sharedTest/java/co/omise/android/ui/PaymentCreatorActivityTest.kt

Added `FLAG_SECURE` to these below Activity classes to prevent screenshot.
- CreditCardActivity
- PaymentCreatorActivity
- AuthorizingPaymentActivity

[MIT-1845] Add FLAG_SECURE

---

app/src/java/java/co/omise/android/example/CheckoutActivity.java
app/src/main/res/values/strings.xml
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt

Enable webview for legacy payments that have `/pay` as ending route in auth url
- Additional result code is introduced to allow integrators to determine if the authentication terminated from webview: 
```
const val WEBVIEW_CLOSED_RESULT_CODE = 5
```

Enable webview for legacy payments

---

README.md

Added a para to state that on payment methods that require opening the external app (e.g. mobile banking app) to authorize the transaction, one must set the return_uri to a deeplink or applink to be able to open the merchant app.

Add deeplink information

---

sdk/src/androidTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt

In case the Netcetera SDk fails to start/initialize the webview will be used to open the authUrl directly.

Fallback to web flow in case Netcetera 3DS SDK fails

---

.github/workflows/ci.yml
sdk/src/androidTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt
sdk/src/main/java/co/omise/android/models/Authentication.kt
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentViewModel.kt
sdk/src/test/java/co/omise/android/ui/AuthorizingPaymentViewModelTest.kt

In the current Netcetera POC branch, we raise errors like OmiseException("Authentication failed.", e)) and sometimes like OmiseException("Authentication failed", e) (note presence of period . on first example). 
In [Fallback to web flow in case Netcetera 3DS SDK fails by AnasNaouchi · Pull Request #286 · omise/omise-android](https://github.com/omise/omise-android/pull/286/files)  we do certain actions based on exception raised; the lack of restriction on allowed values will likely lead to bugs.
This PR replaces literal strings with enums where possible.

Replace strings with enums

---

README.md
app/src/java/java/co/omise/android/example/CheckoutActivity.java
app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt
app/src/main/AndroidManifest.xml
app/src/main/java/co/omise/android/example/PaymentResultActivity.kt
sdk/src/androidTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentViewModel.kt
sdk/src/test/java/co/omise/android/ui/AuthorizingPaymentViewModelTest.kt

Add the ability to pass `threeDSRequestorAppURL` from the merchant app to the SDK using extra intent in the `AuthorizingPaymentActivity` :
```kotlin
putExtra(
EXTRA_THREE_DS_REQUESTOR_APP_URL,
"sampleapp://omise.co/authorize_return"
)
```

Pass params from merchant to sdk

---

sdk/src/main/java/co/omise/android/models/Item.kt

Atome source api call was failing due to an extra parameter named `stability` being sent in the body request coming from the `Parcelable` class. 
To remove that parameter and make the api call successful we added an ignore annotation to remove the `stability` parameter 
*NOTE:*
- This behavior was not observed on physical devices but it may happen
- This edit was added to avoid breaking the Atome source api call since the api does not accept additional parameters on the item level
Similar issue: https://stackoverflow.com/questions/77639841/a-field-stability-is-added-in-my-parcelable-classes
Re-run the release job for the previous version from github actions and complete the process in nexus repo manager

Ignore `stability` field when parsing `item` to json in Atome

---

app/src/main/AndroidManifest.xml
bankapp/build.gradle
build.gradle
sdk/src/main/java/co/omise/android/ui/CreditCardEditText.kt
testsupport/build.gradle

Upgrade the target sdk and the compile sdk to level 34 as a part of the overall upgrade initiatives.
*NOTE:*
The upgrade was performed on the POC branch as in master we faced some problems:
- Android SDK level 34 required that certain edits for any usage of `PendingIntent` must be performed but this code is not used in the SDK directly but it is part of another library `co.omise:threeds-android` that is no longer used in the SDK but is still a dependency as it is required in some parts of the app like cutom UI in the SDK. Removal of the library was not successful as it is needed for custom UI implementation by the merchant.
- Another attempt was to actually edit the code of the library but complications arose preventing local usage of the library and even if that did not happen we will …

Upgrade targetSDKLevel and compileSDKLevel to 34

---

app/src/java/java/co/omise/android/example/CheckoutActivity.java
app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt
sdk/build.gradle
sdk/src/androidTest/java/co/omise/android/ui/PaymentCreatorActivityTest.kt
sdk/src/main/java/co/omise/android/extensions/IntentExtensions.kt
sdk/src/main/java/co/omise/android/models/Capability.kt
sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
sdk/src/main/java/co/omise/android/models/SourceType.kt
sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt
sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
sdk/src/main/res/layout/activity_payment_creator.xml
sdk/src/main/res/values-ja/strings.xml
sdk/src/main/res/values-th/strings.xml
sdk/src/main/res/values/strings.xml

Enhancement:
- Load the capability object from the SDK side and the merchant is no longer required to load in the app using the SDK
- Hard coded values like the `installment_terms` and some lists of banks have been removed and are now loaded from capabilities.
- Cross filter payment methods between capabilities and merchant request, ex:
merchant requests methods 1,2,3
capability contains methods 2,3
result: 2,3 are displayed

Load intallment terms from capabilities

---

sdk/src/androidTest/java/co/omise/android/ui/PaymentCreatorActivityTest.kt
sdk/src/main/java/co/omise/android/models/Capability.kt
sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt
sdk/src/test/java/co/omise/android/TokenizationMethodTest.kt

In some cases the tokenization methods were displayed when not requested and in order to avoid such cases, the filtering has been centralized to only be in the `filterCapabilities` function and removed from the `init` of the capabilities model.

Fix tokenization methods filtering

---

README.md
app/build.gradle
app/proguard-rules.pro
sdk/build.gradle
sdk/src/main/java/co/omise/android/ThreeDS2ServiceWrapper.kt
sdk/src/main/java/co/omise/android/ThreeDSConfigProvider.kt
sdk/src/main/java/co/omise/android/models/NetceteraConfig.kt
sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentViewModel.kt
sdk/src/test/java/co/omise/android/ui/AuthorizingPaymentViewModelTest.kt
sdk/src/test/java/co/omise/android/ui/ThreeDsConfigProviderTest.kt

Fix the issue when using the SDK in release mode for version v5.x till v5.3.0 . 
If the integrator was using pro guard and trying to access the auth uri flow using native 3ds flow, then the SDK will crash since some classes were missing during the R8 process/proguard obfuscation.

Fix 3ds auth release mode

---

sdk/src/main/java/co/omise/android/ui/CreditCardEditText.kt

Set card brand back to public to allow merchants to access the card brand from the card number textfield. 
closes #357

Set card brand variable to public
