README.ja.md, README.md, omise-android_Example/src/co/omise_android_test/ConnectOmiseActivity.java, omise-android_Example/src/co/omise_android_test/IslandActivity.java, omise-android_SDK/src/co/omise/Card.java, omise-android_SDK/src/co/omise/JsonParser.java, omise-android_SDK/src/co/omise/Omise.java
Add the missing `setSecurityCode` in token request and properly set `securityCodeCheck` in JSON parser.
=> Add security code field to token request

omise-android-lib/omise-android/build.gradle, omise-android-lib/omise-android/src/main/java/co/omise/Card.java, omise-android-lib/omise-android/src/main/java/co/omise/JsonParser.java, omise-android-lib/omise-android/src/main/java/co/omise/Omise.java
Add new User-Agent to HTTP HEADER and change running to 1.0.3
=> Featurenew library

app/build.gradle, sdk/build.gradle, sdk/src/main/java/co/omise/android/Client.java, sdk/src/main/java/co/omise/android/TLSSocketFactory.java, sdk/src/main/java/co/omise/android/ui/CreditCardActivity.java
For more information please go to https://github.com/square/okhttp/issues/1934
=> Enable TLS 1.2 in Android prior to 5.0.0

sdk/src/main/res/values-ja/strings.xml, sdk/src/main/res/values-th/strings.xml, sdk/src/main/res/values/strings.xml
=> Fixed: 'placeholder_security_code' untranslatable warning

sdk/src/main/java/co/omise/android/Client.java
Update `User-Agent` to `OmiseAndroid/2.6.1 Android/26 Model/Nexus 5X` format.
=> Update user agent.

README.md, app/build.gradle, app/proguard-rules.pro, app/src/main/res/values/strings.xml, sdk/build.gradle, sdk/src/main/java/co/omise/android/models/Card.java, sdk/src/test/java/co/omise/android/CardModelTest.java
- Added `bank, country` fields to Card object.
- Updated ProGuard rules to fixed OkHttp warning when release app.
=> Add bank, country field to Card object

CHANGELOG.md, README.md, sdk/build.gradle
=> Release version 2.6.3

sdk/src/main/java/co/omise/android/models/CardParam.kt, sdk/src/main/java/co/omise/android/models/Token.kt, sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt
**TASK**=>T14296
**SUMMARY**
Small PR where we changed the way the Request body is serialized and added to it from manually creating a FormBody to using our Serializer. 
**QA** 
Token creation (in example app) should proceed as before.
=> Changed Token request body serialization

app/build.gradle, build.gradle, sdk/build.gradle
Cleanup duplicated declaring dependencies and declared dependency version variables for reusable.
=> Simplify Gradle file

.circleci/config.yml
**TASK**=> T13623
**SUMMARY**
Added CircleCi configuration 
👾**Note** 👾
We are still not getting a pass from CircleCi but that is because there are failing tests and not because there is no configuration.
=> Circle ci integration

sdk/src/main/java/co/omise/android/models/FlowType.kt, sdk/src/main/java/co/omise/android/models/Source.kt, sdk/src/main/java/co/omise/android/models/SourceType.kt
To fix the source response failed to deserialize `type` and `flow` cause the response not match with the instance creator function.
Corrected checking response field value and return `Unknown` with raw value if not match any `SourceType` or `FlowType`.
=> Fix deserialize source response

.circleci/config.yml, sdk/src/test/java/co/omise/android/CardModelTest.java
Updated Circle Ci configure from #73
=> Update Circle ci config

sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt, sdk/src/main/java/co/omise/android/ui/EContextFormFragment.kt, sdk/src/main/java/co/omise/android/ui/InstallmentChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/InternetBankingChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/OmiseListFragment.kt, sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt, sdk/src/main/res/layout/fragment_econtext_form.xml, sdk/src/main/res/values-ja/strings.xml, sdk/src/main/res/values-th/strings.xml, sdk/src/main/res/values/strings.xml
In this PR translated the SDK to support Thai and Japan.
=> Translate payment creator

sdk/src/main/java/co/omise/android/models/SourceType.kt, sdk/src/main/java/co/omise/android/ui/EContextFormFragment.kt, sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt, sdk/src/sharedTest/java/co/omise/android/ui/EContextFormFragmentTest.kt
Added **Pay with Points** source type. Also, changed source type `EContext` to `Econtext`.
=> Added 'points' source type.

app/src/main/res/values/strings.xml, sdk/src/androidTest/java/co/omise/android/ui/CreditCardActivityInstrumentedTest.kt, sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt, sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt, sdk/src/main/res/layout/activity_credit_card.xml, sdk/src/main/res/values-ja/strings.xml, sdk/src/main/res/values-th/strings.xml, sdk/src/main/res/values/strings.xml, sdk/src/test/java/co/omise/android/extensions/APIErrorExtensionsTest.kt
Updated textual from QA feedback.
=> Textual changes

app/src/java/java/co/omise/android/example/CheckoutActivity.java, app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt, app/src/main/java/co/omise/android/example/PaymentSetting.kt, app/src/main/java/co/omise/android/example/PaymentSettingFragment.kt, sdk/src/main/java/co/omise/android/models/Capability.kt, sdk/src/main/java/co/omise/android/models/PaymentMethod.kt
In this PR created a helper function to create an instance of the Capability.
=> Create capability instance

sdk/src/main/java/co/omise/android/api/Client.kt, sdk/src/main/java/co/omise/android/api/EndPoint.kt, sdk/src/test/java/co/omise/android/EndpointTest.java
Removed certificate pinning from the Client. Same in the #70
=> Remove certificate pinning

app/src/java/java/co/omise/android/example/CheckoutActivity.java, app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt, sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt, sdk/src/test/java/co/omise/android/extensions/APIErrorExtensionsTest.kt
Capitalized the error messages from the API.
=> Capitalize the error messages

app/src/main/java/co/omise/android/example/PaymentSetting.kt, sdk/src/main/java/co/omise/android/models/Capability.kt
Fixed weird ordering and wrong payment methods when used specific payment methods.
=> Fix settings

README.md, app/src/main/res/values/styles.xml
In this PR updated the code snippet to show the item text customization.
=> Update theme customization doc

sdk/src/main/java/co/omise/android/models/Barcode.kt, sdk/src/main/java/co/omise/android/models/Document.kt, sdk/src/main/java/co/omise/android/models/ModelTypeResolver.kt, sdk/src/main/java/co/omise/android/models/Source.kt, sdk/src/main/java/co/omise/android/models/SourceType.kt, sdk/src/test/java/co/omise/android/SerializationTest.java, sdk/src/test/resources/data/objects/barcode_object.json, sdk/src/test/resources/data/objects/document_object.json, sdk/src/test/resources/data/objects/source_object.json
To support creating a source with new source types **PayNow** and **PromptPay**.
In this PR add new source types **PayNow** and **PromptPay**. Also, add new properties `zeroInterestInstallments` and `scannableCode` to **Source** object.
When create a source with new source type should receive success response.
N/A
N/A
Normal
=> T20177 - Support new source types

sdk/src/main/java/co/omise/android/models/References.kt, sdk/src/test/resources/data/objects/source_object.json
To add new fields to `References` model.
Removed `Model` implementation in `References` model. And add new fields `deviceId, customerAmount, customerCurrency, customerExchangeRate, paymentCode`.
If there is a `references` data in the Source API response, the `Source.refereces` field must not null.
N/A
N/A
Normal
=> T20268 - Update References's fields

README.md
To add the docs about how create the Capability object to customize the `PaymentCreatorActivity`'s payment methods.
Added docs and sample code to show about creating the Capability object from the helper function.
N/A
N/A
N/A
Low/Normal/High
=> T20847 - Add docs about customize the payment methods in the PaymentCreatorActivity

CHANGELOG.md, build.gradle
To prepare project for release new version.
- Bump version to 3.1.0
- Add change logs for changed things in this version
N/A
N/A
N/A
Normal
=> T20852 - Release version 3.1.0

README.md
Very small bitflip to instructions
=> Update README to reflect latest version

build.gradle
To fix a potential security from using `jackson-core` version `2.9.9`.  #136 
Updated `jackson-core` to latest version.
N/A
N/A
N/A
High
=> Update Jackson lib

CHANGELOG.md, README.md, build.gradle
To release the patch version that includes fixed this issue #136 .
This PR includes #137 that fixed the issue #136 .
Also, bumped version and updated **CHANGELOG.md** .
N/A
N/A
N/A
High
=> Release version 3.1.1

CHANGELOG.md, build.gradle
In this PR bump the version and update the CHANGELOG.md for releasing version 3.1.2.
=> Prepare release version 3.1.2

README.md
Update version number on the README.md to the same with the release version number.
=> Update version number on the README.md

README.md
Simplify SDK version on the README.
Changed declaring SDK version on the README to range pattern.
N/A
N/A
N/A
Normal
=> Change declaring SDK version on the README to range pattern

sdk/src/main/java/co/omise/android/api/RequestBuilder.kt, sdk/src/main/java/co/omise/android/models/ChargeStatus.kt, sdk/src/main/java/co/omise/android/models/Token.kt, sdk/src/test/resources/data/objects/token_object.json
This PR purpose to support the retrieving a token request.
In this PR create the `GetTokenRequestBuilder` to retrieve a token from the ID. Also, add the `charge_status` field to Token model.
**Request sample:** 
```
val tokenrequest = Token.GetTokenRequestBuilder("tokn_test_1234").build()
client.send(tokenrequest, object :RequestListener<Token> {
override fun onRequestSucceed(model: Token) {
...
}
override fun onRequestFailed(throwable: Throwable) {
...
}
})
```
N/A
N/A
N/A
N/A
N/A
=> Retrieving a token request

CHANGELOG.md, build.gradle
Prepare version and CHANGELOG.md for releasing version 3.1.3
- Bump version to 3.1.3
- Update CHANGELOG.md
N/A
N/A
N/A
N/A
N/A
N/A
=> Release version 3.1.3

build.gradle, sample-threeds-v2-app/src/main/java/co/omise/android/example/CheckoutActivity.kt, sample-threeds-v2-app/src/main/java/co/omise/android/example/PaymentProcessingActivity.kt, sample-threeds-v2-app/src/main/java/co/omise/android/example/PaymentResultActivity.kt, sdk/src/main/java/co/omise/android/api/Configurer.kt, sdk/src/main/java/co/omise/android/api/Invocation.kt, sdk/src/main/java/co/omise/android/api/RequestBuilder.kt, sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt, sdk/src/sharedTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt
This PR purposes to upgrade Okhttp to version 4.
Migrated the project to use Okhttp 4 for networking code.
N/A
N/A
N/A
N/A
N/A
N/A
=> Upgrade Okhttp 4

README.md, app/src/java/java/co/omise/android/example/CheckoutActivity.java, app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt, docs/3d-secure-v2.md, sdk/src/main/java/co/omise/android/config/AuthorizingPaymentConfig.kt, sdk/src/main/java/co/omise/android/config/ThreeDSConfig.kt, sdk/src/main/java/co/omise/android/config/UiCustomization.kt
This PR purposes to write documentation for 3DS v2.
- Create `docs/3d-secure-v2.md` that contains about how to implement the 3DS v2 in the merchant application.
- Write document to the source code.
N/A
N/A
N/A
N/A
N/A
N/A
=> Update 3DS v2 docs

.github/workflows/cd.yml
To fix the failure from auto upload archive to Sonatype for releasing the new version.
Removed specific module from upload archive command.
N/A
N/A
N/A
N/A
N/A
N/A
=> Fix release build

README.md, app/src/java/java/co/omise/android/example/CheckoutActivity.java, app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt, docs/3d-secure-v2.md, sdk/src/main/java/co/omise/android/config/AuthorizingPaymentConfig.kt, sdk/src/main/java/co/omise/android/config/ThreeDSConfig.kt, sdk/src/main/java/co/omise/android/config/UiCustomization.kt
=> Recover 3DS v2 docs

README.md
=> Remove reference to forum and add link to build status

.github/workflows/ci.yml
Enable automated UI testing for Omise-Android and enable test reporting
-UI testing is already enabled through Robotium framework
-Added test reports. After every test, report will be generated in the `Artifacts` section where detailed report of failing tests can be found.
-Changed the way the tests are triggered on Github, so that the Github Actions doesn't run same actions twice on every push.
=> Update test workflow

app/src/main/java/co/omise/android/example/PaymentSetting.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preference_payment_setting.xml, sdk/src/main/java/co/omise/android/models/SourceType.kt, sdk/src/main/java/co/omise/android/ui/PaymentMethodResources.kt, sdk/src/main/res/values-ja/strings.xml, sdk/src/main/res/values-th/strings.xml, sdk/src/main/res/values/strings.xml, sdk/src/sharedTest/java/co/omise/android/ui/InstallmentChooserFragmentTest.kt, sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
Add Ezypay installment to the sdk
=> [EM-559] Add Ezypay to Android sdk

CHANGELOG.md
release a new version v4.0.0-alpha02 that with Ezypay installment payment added
=> v4.0.0-alpha02

build.gradle
v4.0.0-alpha02 &  update gradle
=> v4.0.0-alpha02 update gradle

CHANGELOG.md, build.gradle
Bump code and SDK version before publishing to Maven Central.
=> Release v4.0.0-alpha03

CHANGELOG.md, build.gradle
v4.0.0-alpha05 release for KBank and OCBC Pay Anyone mobile banking supports
=> Release v4.0.0-alpha05

CHANGELOG.md, build.gradle
v4.0.0-alpha06 release for KBank mobile banking logo and title updated.
=> v4.0.0-alpha06 release

app/src/main/java/co/omise/android/example/PaymentSetting.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preference_payment_setting.xml, sdk/src/main/java/co/omise/android/models/SourceType.kt, sdk/src/main/java/co/omise/android/ui/PaymentMethodResources.kt, sdk/src/main/res/values-ja/strings.xml, sdk/src/main/res/values-th/strings.xml, sdk/src/main/res/values/strings.xml, sdk/src/sharedTest/java/co/omise/android/ui/MobileBankingChooserFragmentTest.kt, sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
- Add Bay mobile banking supports.
Task : https://omise.atlassian.net/browse/APM2-452
=> Add support mobile banking bay

CHANGELOG.md, build.gradle
v4.0.0-alpha07 release for BAY mobile banking.
=> v4.0.0-alpha07 release(mobile banking bay)

CHANGELOG.md, build.gradle
* **ADDED:** Support for GooglePay
* **ADDED:** Support for BBL mobile banking 
* **CHANGED:** Logo and label for mobile banking payments: Kbank (TH), Bay (TH) and SCB (TH)
=> V4.1.0 Release

app/src/main/java/co/omise/android/example/PaymentSetting.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preference_payment_setting.xml, sdk/src/main/java/co/omise/android/models/SourceType.kt, sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/PaymentMethodResources.kt, sdk/src/sharedTest/java/co/omise/android/ui/MobileBankingChooserFragmentTest.kt, sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
Move OCBC Pay Anyone out of `Mobile banking` to be at first-level payment option.
Task: https://omise.atlassian.net/browse/APM2-716
=> [APM2-716] Move OCBC Pay Anyone to be at first-level payment option

CHANGELOG.md, build.gradle
* **CHANGED:** Move OCBC Pay Anyone payment out of Mobile Banking section.
=> release 4.1.2

CHANGELOG.md, build.gradle
* **CHANGED:** Added support for GrabPay payment method.
=> Release v4.1.3

CHANGELOG.md, build.gradle
* **ADDED:** Added support ShopeePay JumpApp.
=> Release v4.3.0

CHANGELOG.md, README.md, app/proguard-rules.pro, build.gradle, gradle/wrapper/gradle-wrapper.properties, sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt
- fix: remove deprecated JCenter
- fix: update gradle 7.5.1
- docs: update proguard rules
- feat: switch to authorize with WebView
- feat: bump sdk version and remove jcenter
=> Switch to authorize with browser flow

app/src/main/java/co/omise/android/example/PaymentSetting.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preference_payment_setting.xml, sdk/src/main/java/co/omise/android/models/SourceType.kt, sdk/src/main/java/co/omise/android/ui/PaymentMethodResources.kt, sdk/src/main/res/values-ja/strings.xml, sdk/src/main/res/values-th/strings.xml, sdk/src/main/res/values/strings.xml, sdk/src/sharedTest/java/co/omise/android/ui/InstallmentChooserFragmentTest.kt, sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
* An option for Maybank Installment is selectable on Android SDK.
* Deprecated Installment Ezypay
=> [EM-2604] Added installment Maybank and deprecated installment Ezypay

CHANGELOG.md, build.gradle
ADDED: Installment Maybank for Malaysian merchants
REMOVED: Unused and deprecated Installment Ezypay
=> Release 4.4.0

CHANGELOG.md, build.gradle
* **CHANGED:** Logo and label for Lotus Bill Payment
=> Release 4.4.2

CHANGELOG.md, build.gradle
* **ADDED:** Added support for Atome payment method
Related PR: https://github.com/omise/omise-android/pull/239
=> 4.5.0 Release

CHANGELOG.md, build.gradle
* **CHANGED:** Update logo and name of Lotus's Bill Payment
Related PR: https://github.com/omise/omise-android/pull/242
=> 4.5.2 Release

CHANGELOG.md, build.gradle
* **ADDED:** Added support for Krungthai NEXT (mobile_banking_ktb) payment method
=> v4.6.0 release

CHANGELOG.md, build.gradle
ADDED: Added support for PayPay payment method
Related PR: https://github.com/omise/omise-android/pull/249
=> v4.7.0 Release

CHANGELOG.md, build.gradle
REMOVED: Removed support for SCB and KTB Internet Banking payment method
=> Release v4.8.0

app/src/main/AndroidManifest.xml, sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt, sdk/src/main/java/co/omise/android/extensions/EditTextExtensions.kt, sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt, sdk/src/main/java/co/omise/android/ui/CreditCardEditText.kt, sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt, sdk/src/main/java/co/omise/android/ui/TrueMoneyFormFragment.kt, testsupport/src/main/AndroidManifest.xml
Jira ticket: https://opn-ooo.atlassian.net/browse/ENGA3-877
=> [ENGA3-877] Resolve SonarCloud issues

.github/workflows/ci.yml, .github/workflows/coverage.yml, build.gradle, sdk/build.gradle, sdk/src/androidTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt, sdk/src/androidTest/java/co/omise/android/ui/CreditCardActivityInstrumentedTest.kt, sdk/src/sharedTest/java/co/omise/android/ui/CreditCardActivityTest.kt, sdk/src/sharedTest/java/co/omise/android/ui/EContextFormFragmentTest.kt, sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt, sdk/src/sharedTest/java/co/omise/android/ui/TrueMoneyFormFragmentTest.kt
- Run instrumentation tests to CI flow
- Create coverage report to SonarCloud (43.9% coverage)
=> [MIT-1510] Coverage report

app/src/main/java/co/omise/android/example/PaymentSetting.kt, app/src/main/res/values/strings.xml, sdk/src/main/java/co/omise/android/models/SourceType.kt, sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/PaymentMethodResources.kt, sdk/src/main/res/values-ja/strings.xml, sdk/src/main/res/values-th/strings.xml, sdk/src/main/res/values/strings.xml, sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
Replace TrueMoney with TrueMoneyJumpApp where available
=> Replace TrueMoney with TrueMoneyJumpApp where available

CHANGELOG.md, app/src/main/java/co/omise/android/example/PaymentSetting.kt, app/src/main/res/values/strings.xml, build.gradle, sdk/src/main/java/co/omise/android/models/SourceType.kt, sdk/src/main/java/co/omise/android/ui/PaymentChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/PaymentMethodResources.kt, sdk/src/main/res/values-ja/strings.xml, sdk/src/main/res/values-th/strings.xml, sdk/src/main/res/values/strings.xml, sdk/src/sharedTest/java/co/omise/android/ui/PaymentChooserFragmentTest.kt
Keep POC branch up to date with master for easier merge when POC is ready.
=> Sync POC with master

sdk/src/main/java/co/omise/android/extensions/EditTextExtensions.kt, sdk/src/main/java/co/omise/android/ui/ExpiryDateEditText.kt
The callbacks from the official docs are here:
https://developer.android.com/reference/android/text/TextWatcher
=> Remove nullability from text field call backs

CHANGELOG.md, build.gradle
=> Bump v4.13.1

CHANGELOG.md, build.gradle
=> Bump v4.14.0

CHANGELOG.md, build.gradle
=> Bump v4.15.0

sdk/src/main/java/co/omise/android/extensions/APIErrorExtensions.kt, sdk/src/main/res/values-ja/strings.xml, sdk/src/main/res/values-th/strings.xml, sdk/src/main/res/values/strings.xml
Display proper error message when absorption or source type is not supported
=> Fix error message

sdk/src/main/java/co/omise/android/EncryptionUtils.kt, sdk/src/main/java/co/omise/android/ThreeDS2ServiceWrapper.kt, sdk/src/main/java/co/omise/android/models/NetceteraConfig.kt, sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentViewModel.kt, sdk/src/test/java/co/omise/android/ui/AuthorizingPaymentViewModelTest.kt, sdk/src/test/java/co/omise/android/ui/EncryptionUtilsTest.kt
Replace hard coded Netcetera config values with endpoint values
=> Add 3ds config endpoint

CHANGELOG.md, build.gradle
=> Bump v4.15.1

sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt
Add a condition to check if the auth url requires 3DS processing. If not open web view.
=> Add acs check

sdk/src/main/java/co/omise/android/models/Authentication.kt, sdk/src/main/java/co/omise/android/models/NetceteraConfig.kt, sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentViewModel.kt, sdk/src/test/java/co/omise/android/ui/AuthorizingPaymentViewModelTest.kt
Replace hard coded `messageVersion` and `acsReferenceNumber` with values from backend.
=> Update Auth and Config models

sdk/src/main/java/co/omise/android/ThreeDSConfigProvider.kt, sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt, sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentViewModel.kt, sdk/src/test/java/co/omise/android/ui/AuthorizingPaymentViewModelTest.kt, sdk/src/test/java/co/omise/android/ui/ThreeDsConfigProviderTest.kt
Handle config endpoint errors and switch to webview when encountering an error .
=> Handle config endpoint error and unavailability

CHANGELOG.md, build.gradle
=> Bump v4.16.1

build.gradle
Increment code version for release
=> Increment code version

README.md, app/src/java/java/co/omise/android/example/CheckoutActivity.java, app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt, sdk/src/androidTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt, sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt, sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentViewModel.kt
Set `ThreeDSRequestorAppURL` param to optional as recommended by 3DS provider.
=> Set ThreeDSRequestorAppURL as optional

app/src/java/java/co/omise/android/example/CheckoutActivity.java, app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt, app/src/main/java/co/omise/android/example/PaymentSetting.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preference_payment_setting.xml, sdk/src/main/java/co/omise/android/models/SourceType.kt, sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt, sdk/src/main/java/co/omise/android/ui/InstallmentChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/OmiseActivity.kt, sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt, sdk/src/main/java/co/omise/android/ui/PaymentMethodResources.kt, sdk/src/sharedTest/java/co/omise/android/ui/InstallmentTermChooserFragmentTest.kt
Implement the new source `installment_wlb_ktc ` following [OPN docs](https://docs.opn.ooo/installment-white-label-payments)
=> Implement ktc wlb source

CHANGELOG.md, build.gradle
Implement `installment_wlb_ktc` source. More info at [OPN docs](https://docs.opn.ooo/installment-white-label-payments)
=> Bump v4.17.1

README.md, app/src/java/java/co/omise/android/example/CheckoutActivity.java, app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt, sdk/src/androidTest/java/co/omise/android/ui/AuthorizingPaymentActivityTest.kt, sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt, sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentViewModel.kt
Reverts omise/omise-android#331
=> Revert "Set ThreeDSRequestorAppURL as optional"

CHANGELOG.md, README.md, build.gradle
Bump v5.0.0 and highlight breaking changes.
=> Bump v5.0.0

.github/workflows/cd.yml, .github/workflows/ci.yml
Upgrade java version in CI to zulu 21
=> Upgrade java to zulu 21 in CI/CD

.github/workflows/cd.yml, .github/workflows/ci.yml
Unit tests in CI/CD are stuck in java 21. Moving to java 17 until the issue is solved.
=> Downgrade jdk to 17

.github/workflows/cd.yml, .github/workflows/ci.yml
Debug unit tests in CD workflow
=> Fix stuck unit tests

sdk/build.gradle
Replace empty string with null to fix error `No signature of method` was found.
=> Fix publish build

README.md, app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt, app/src/main/java/co/omise/android/example/PaymentSetting.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preference_payment_setting.xml, sdk/src/main/java/co/omise/android/models/SourceType.kt, sdk/src/main/java/co/omise/android/ui/CreditCardActivity.kt, sdk/src/main/java/co/omise/android/ui/InstallmentChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/PaymentCreatorActivity.kt, sdk/src/main/java/co/omise/android/ui/PaymentMethodResources.kt
Implement the following sources:
`installment_wlb_bay `
`installment_wlb_bbl `
`installment_wlb_first_choice `
`installment_wlb_kbank `
`installment_wlb_scb `
`installment_wlb_ttb `
More info at [OPN docs](https://docs.opn.ooo/installment-white-label-payments)
=> Add wlb source all banks

CHANGELOG.md, build.gradle
=> Bump 5.1.0

sdk/src/androidTest/AndroidManifest.xml, sdk/src/androidTest/java/co/omise/android/ui/AtomeFormFragmentTest.kt, sdk/src/androidTest/java/co/omise/android/ui/GooglePayActivityTest.kt
Add tests for AtomeFragment and GooglePayActivity
=> Increase tests coverage

CHANGELOG.md, README.md, build.gradle, sdk/src/androidTest/java/co/omise/android/ui/AtomeFormFragmentTest.kt
=> Bump v5.2.0

CHANGELOG.md, build.gradle
=> Bump v5.3.0

CHANGELOG.md, build.gradle
=> Bump v5.4.0

app/src/main/java/co/omise/android/example/PaymentSetting.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preference_payment_setting.xml, sdk/src/main/java/co/omise/android/models/SourceType.kt, sdk/src/main/java/co/omise/android/ui/InstallmentTermChooserFragment.kt, sdk/src/main/java/co/omise/android/ui/PaymentMethodResources.kt
Add `installment_wlb_uob` source support.
=> Add uob_wlb_installment

CHANGELOG.md, build.gradle
=> Bump v5.5.0

.github/workflows/ci.yml, .github/workflows/cleanup-builds.yml, .github/workflows/distribution.yml, app/proguard-rules.pro, app/src/kotlin/java/co/omise/android/example/CheckoutActivity.kt, scripts/cleanup_builds.sh, sdk/build.gradle
Add auto release scripts and workflows to publish the android example app to firebase app distribution.
=> Auto release example app

.github/workflows/cd.yml, build.gradle, sdk/build.gradle
Update the maven release process as legacy Nexus ossrh has been deprecated.
=> Update maven release

.github/workflows/ci.yml, build.gradle, sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt, sdk/src/main/java/co/omise/android/ui/GooglePayActivity.kt, sdk/src/main/java/co/omise/android/ui/OmiseActivity.kt
Handle edge to edge UI overlay.
closes #383
=> Handle UI overlay issues when edge to edge mode is enabled

CHANGELOG.md, README.md, build.gradle
Bump v6.0.0-alpha.1 and update readme with breaking changes
=> Bump v6.0.0 alpha.1
